#!/usr/bin/env bash
# This script configures Nginx to include a custom HTTP header X-Served-By with the hostname of the server

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx to add custom header
sudo sed -i '/server_name _;/ a \        add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
