#!/usr/bin/env bash
# This script configures Nginx to include a custom HTTP response header

set -e

# Update package repository and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx to include custom HTTP response header
sudo sed -i 's/^http {/http {\n\tadd_header X-Served-By $hostname;/' /etc/nginx/nginx.conf

# Restart Nginx
sudo service nginx restart

# Ignore SC2154 error from Shellcheck
# shellcheck disable=SC2154
