#!/usr/bin/env bash
# Description: What type of network a computer in local is connected to?
echo "3"
# Description: type of network that connect office in a building to another office in a building a few streets away?
echo "2"
# Description: What network do you use when you browse www.google.com from your smartphone?
echo "1"
