#!/usr/bin/env bash
# Description: Which statement is correct for the TCP box:
echo "1"
# Description: Which statement is correct for the UDP box:
echo "2"
# Description: Which statement is correct for the TCP worker:
echo "2"
