#!/usr/bin/env bash
# The script displays a list of the running processes.
printf "%-10s %-5s %-5s %-10s %-10s %-10s %-10s %-5s %-10s %s\n" "USER" "PID" "%CPU" "%MEM" "VSZ" "RSS" "TTY" "STAT" "START" "TIME"
