#!/usr/bin/env bash
#!/usr/bin/env bash

# Create PID file and handle signals
sudo bash -c 'echo $$ > /var/run/myscript.pid'
trap "sudo rm -f /var/run/myscript.pid; exit" SIGQUIT
trap "sudo rm -f /var/run/myscript.pid; echo I hate the kill command; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT

# Loop to display "To infinity and beyond"
while :
do
    echo "To infinity and beyond"
    sleep 2
done
